# Use python image
FROM python:3.10

# Args
#ARG MONGO_CLUSTER
#ENV MONGO_CLUSTER=$MONGO_CLUSTER
#ARG REDIS_URL
#ENV REDIS_URL=$REDIS_URL
#ARG HASH_ALGORITHM
#ENV HASH_ALGORITHM=$HASH_ALGORITHM
#ARG SECRET_KEY
#ENV SECRET_KEY=$SECRET_KEY
#ARG CNAMBOT_EMAIL
#ENV CNAMBOT_EMAIL=$CNAMBOT_EMAIL
#ARG CNAMBOT_PASSWORD
#ENV CNAMBOT_PASSWORD=$CNAMBOT_PASSWORD
#ARG SESSION_TYPE
#ENV SESSION_TYPE=$SESSION_TYPE
#ARG PERMANENT_SESSION_LIFETIME
#ENV PERMANENT_SESSION_LIFETIME=$PERMANENT_SESSION_LIFETIME

# Use this folder as working directory
WORKDIR /app

# Install requirements
COPY . /app/
RUN pip install -r requirements.txt
RUN pip install frtk-0.1.0.tar.gz

# Run service
CMD ["python", "app.py"]
