import string
import random
import smtplib
from os import getenv
from pymongo import MongoClient
from email.utils import formatdate
from email.message import EmailMessage
from passlib.context import CryptContext

# =================================================== VARIABLES =================================================== #


# Env var
SECRET_KEY = getenv("SECRET_KEY")

# DB file
client = MongoClient(getenv("MONGO_CLUSTER"))
db = client.cnambot

# Hashing
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

# Characters to generate password from
characters = list(string.ascii_letters + string.digits + string.punctuation)


# =============================================== PASSWORDS FUNCTIONS =============================================== #


def pwd_generator() -> str:
    """
    Description: Generates a password for those user who have no idea
    :return: Password generated by the func
    """
    random.shuffle(characters)
    password = [random.choice(characters) for _ in range(10)]
    random.shuffle(password)
    return "".join(password)


def verify_password(plain_password: str, hashed_password: str):
    """
    Description:
    :return:
    """
    return pwd_context.verify(plain_password, hashed_password)


def get_password_hash(password: str) -> str:
    """
    Description:
    :param password
    :return:
    """
    return pwd_context.hash(password)


# =============================================== DATABASES FUNCTIONS =============================================== #


def create_user(username: str, promo: str, email: str, pwd: str, tmp: bool = False):
    """
    Description: Basic function to create a json file for a new user, temporary or not.
    :param username: Unique username
    :param promo: Promotion to choose in a drop-down list
    :param email: CNAM email
    :param pwd: Password to hash
    :param tmp: Temporary parameter used to create an entry in tmp_users if true or users by default if false
    """
    if tmp:
        db.tmp_users.insert_one({
            "username": username,
            "promo": promo,
            "email": email,
            "password": get_password_hash(pwd),
        })
    else:
        db.users.insert_one({
            "username": username,
            "promo": promo,
            "email": email,
            "password": get_password_hash(pwd),
        })


def user_in_db(name: str, email: str):
    """
    Description:
    :param name:
    :param email:
    :return: Error message to print on user screen if the user already exist
    """
    for doc in db.users.find():
        if name == doc["username"] and email == doc["email"]:
            return "Ce nom d'utilisateur et cette adresse email sont déjà utilisés sur CnamBot !"
        if name == doc["username"]:
            return "Ce nom d'utilisateur est déjà pris sur CnamBot !"
        if email == doc["email"]:
            return "Cette adresse email est déjà utilisée sur CnamBot !"
    return


# ============================================= EMAIL RELATED FUNCTIONS ============================================= #


def send_email(email: str, option: str):
    """
    Description: Function used to send email from CnamBot address when we are validating user email address.
    :param email:
    :param option:
    """
    # Exit func if option param is wrong
    if option not in ["verification", "forgot"]:
        return KeyError("Invalid option for func send_email")

    # Server start and login with credentials
    server = smtplib.SMTP('SMTP.gmail.com', 587)
    server.connect('SMTP.gmail.com', 587)
    server.ehlo()
    server.starttls()
    server.login(getenv("CNAMBOT_EMAIL"), getenv("CNAMBOT_PASSWORD"))

    # Strip eventual space in user address
    email = email.strip()

    # Headers : cnambot_address, user_address, actual_date, subject, message
    msg = EmailMessage()
    msg['From'] = f'CnamBot <{getenv("CNAMBOT_EMAIL")}>'
    msg['To'] = email
    msg["Date"] = formatdate(localtime=True)
    if option == "verification":
        msg['Subject'] = "Votre lien de validation d'email"
        msg.set_content("""\
        Bonjour,
        
        Bienvenue sur CnamBot, voici le lien à suivre pour achever la validation de votre adresse email :
        
        Une fois cela fait, vous pourrez profitez pleinement des services de la plateforme.
        
        Bonne journée,
        L'équipe de développement
        """)
    elif option == "forgot":
        msg['Subject'] = "Votre lien de réinitialisation de mot de passe"
        msg.set_content("""\
        Bonjour,

        Voici votre lien de réinitialisation de mot de passe :

        Bonne journée,
        L'équipe de développement
        """)

    # Trying to send the message, catch if there are any error
    try:
        server.send_message(msg)
        print(option)
        print('{0} : send'.format(email))
    except smtplib.SMTPException as e:
        print(option)
        print('{0} : {1}'.format(email, e))

    server.quit()
