name: lecnambot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Set environment variables
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'lecnambot' }}
  MONGO_CLUSTER: ${{ secrets.MONGO_CLUSTER }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  HASH_ALGORITHM: ${{ secrets.HASH_ALGORITHM }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-20.04
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        heroku container:push web -a $APP_NAME --arg MONGO_CLUSTER=$MONGO_CLUSTER REDIS_URL=$REDIS_URL HASH_ALGORITHM=$HASH_ALGORITHM SECRET_KEY=$SECRET_KEY
        heroku container:release web -a $APP_NAME